baseURL = 'https://advika.dev/'
languageCode = 'en-us'
title = 'advika-blog'

[params]
    dateFormat = "01-02-06"

[HTTPCache]
    [HTTPCache.cache]
        [HTTPCache.cache.for]
            excludes = ['**']
            includes = []